services:
  backend:
    build:
      context: ./mlbackend
      dockerfile: Dockerfile
    ports:
      - 8999:8999
  model:
    build:
      context: ./mlmodels
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    